### ISSUE TITLE
Installation error when trying to install with pip

### ISSUE THREAD

**Issue by gibcheesepuffs** [uqfoundation/multiprocess#113]
$ pip install multiprocessing
```
Defaulting to user installation because normal site-packages is not writeable
Collecting multiprocessing
  Using cached multiprocessing-2.6.2.1.tar.gz (108 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-k0k2xu6t/multiprocessing_322e66545fcf4fcbb6f9ab5027f8bd1e/setup.py", line 94
          print 'Macros:'
          ^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mmckerns** [comment]
`multiprocessing` was integrated into the Python standard library back in Python-2.6 or so... and thus (1) doesn't need to be installed, and (2) the release you are trying to install is not Python-3.x compatible.

If you want to install our fork of `multiprocessing` (i.e. `multiprocess`), then you will need to install it with `pip install multiprocess`.

Please reopen this issue if you feel the issue is not resolved.
