### ISSUE TITLE
Multiprocess does not work with ctypes.Structure

### ISSUE THREAD

**Issue by ot2789** [uqfoundation/multiprocess#114]
Hello!

I am trying the example from the multiprocessing.Value/Array sharing. If I run this code it works:
```
import multiprocessing
import ctypes

class Point(ctypes.Structure):
    _fields_ = (('x', ctypes.c_double), ('y', ctypes.c_double),)

def modify(n, x, s, A):
    n.value **= 2
    x.value **= 2
    s.value = s.value.upper()
    for a in A:
        a.x **= 2
        a.y **= 2

if __name__ == '__main__':
    lock = multiprocessing.Lock()

    n = multiprocessing.Value('i', 7)
    x = multiprocessing.Value(ctypes.c_double, 1.0/3.0, lock=False)
    s = multiprocessing.Array('c', b'hello world', lock=lock)
    A = multiprocessing.Array(Point, [(1.875, -6.25), (-5.75,2.0), (2.375,9.5)], lock=lock)

    p = multiprocessing.Process(target=modify, args=(n, x, s, A))
    p.start()
    p.join()

    print(n.value)
    print(x.value)
    print(s.value)
    print([(a.x, a.y) for a in A])
```

I get:
```
49
0.1111111111111111
b'HELLO WORLD'
[(3.515625, 39.0625), (33.0625, 4.0), (5.640625, 90.25)]
```

However if I switch it to the multiprocess module:

```
import multiprocess as multiprocessing
#import multiprocessing
import ctypes

class Point(ctypes.Structure):
    _fields_ = (('x', ctypes.c_double), ('y', ctypes.c_double),)

def modify(n, x, s, A):
    n.value **= 2
    x.value **= 2
    s.value = s.value.upper()
    for a in A:
        a.x **= 2
        a.y **= 2

if __name__ == '__main__':
    lock = multiprocessing.Lock()

    n = multiprocessing.Value('i', 7)
    x = multiprocessing.Value(ctypes.c_double, 1.0/3.0, lock=False)
    s = multiprocessing.Array('c', b'hello world', lock=lock)
    A = multiprocessing.Array(Point, [(1.875, -6.25), (-5.75,2.0), (2.375,9.5)], lock=lock)

    p = multiprocessing.Process(target=modify, args=(n, x, s, A))
    p.start()
    p.join()

    print(n.value)
    print(x.value)
    print(s.value)
    print([(a.x, a.y) for a in A])
```

I get this:

```
C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py:1845: PicklingWarning: Cannot locate reference to <class '_ctypes.PyCStructType'>.
  warnings.warn('Cannot locate reference to %r.' % (obj,), PicklingWarning)
C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py:1847: PicklingWarning: Cannot pickle <class '_ctypes.PyCStructType'>: _ctypes.PyCStructType has recursive self-references that trigger a RecursionError.
  warnings.warn('Cannot pickle %r: %s.%s has recursive self-references that trigger a RecursionError.' % (obj, obj.__module__, obj_name), PicklingWarning)
Traceback (most recent call last):
  File "dafuck.py", line 26, in <module>
    p.start()
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 901, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 886, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 886, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1838, in save_type
    _save_with_postproc(pickler, (_create_type, (
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1140, in _save_with_postproc
    pickler.save_reduce(*reduction, obj=obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 901, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1838, in save_type
    _save_with_postproc(pickler, (_create_type, (
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1140, in _save_with_postproc
    pickler.save_reduce(*reduction, obj=obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 901, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1530, in save_wrapper_descriptor
    pickler.save_reduce(_getattr, (obj.__objclass__, obj.__name__,
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 886, in save_tuple
    save(element)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\OT\anaconda3\lib\site-packages\dill\_dill.py", line 1851, in save_type
    StockPickler.save_global(pickler, obj, name=obj_name)
  File "C:\Users\OT\anaconda3\lib\pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class '_ctypes.PyCStructType'>: it's not found as _ctypes.PyCStructType

(base) C:\Users\OT\Documents\GitHub\python_basics>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\OT\anaconda3\lib\site-packages\multiprocess\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect

```

Any idea what is going on? Do I need to do something extra to make this work?

Edit, attached the version information:
```
dill version 0.3.5.1
multiprocess version 0.70.13
py version 3.8.8
Windows AMD64 ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
```

**Comment by mmckerns** [comment]
```
Python 3.8.13 (default, May 10 2022, 11:26:38) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.__version__
'0.3.6.dev0'
>>> import multiprocess
>>> multiprocess.__version__
'0.70.14.dev0'
```
I did a quick test of your example on my mac (with the above configuration), and I don't experience the error you are seeing.  I also checked the most recent releases of Python 3.7 - 3.11, and still was not able to reproduce your error.  Note that I didn't try my quick test on windows, and also note that I am using the `dev` releases.  I'll have to check on windows...

**Comment by ot2789** [comment]
Indeed errors does not seem to appear with version 3.9 on windows. Maybe it is a problem related to 3.8? Not sure ...

**Comment by mmckerns** [comment]
I think it's likely the difference between python version 3.8.8 and 3.8.13/14.  Did you try updating your python 3.8?

**Comment by mmckerns** [comment]
If updating your python 3.8 to sync with the version used for multiprocess didn't work, then please reopen this issue and comment.
