### ISSUE TITLE
NotImplementedError: pool objects cannot be passed between processes or pickled

### ISSUE THREAD

**Issue by zhou13** [uqfoundation/multiprocess#18]
I got the following error in python 3.5:
````
>>> import multiprocess
>>> multiprocess.__version__
'0.70.4'
>>> from multiprocess import Pool
>>> p = Pool(4)
>>> p.map(lambda x: (lambda y:y**2)(x) + x, range(10))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    p.map(lambda x: (lambda y:y**2)(x) + x, range(10))
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/pool.py", line 608, in get
    raise self._value
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/pool.py", line 385, in _handle_tasks
    put(task)
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/zhou13/.local/lib/python3.5/site-packages/dill/dill.py", line 793, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/zhou13/.local/lib/python3.5/site-packages/dill/dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
  File "/home/zhou13/.local/lib/python3.5/site-packages/multiprocess/pool.py", line 492, in __reduce__
    'pool objects cannot be passed between processes or pickled'
NotImplementedError: pool objects cannot be passed between processes or pickled
````

**Comment by mmckerns** [comment]
It works for me:
```
Python 3.5.1 (default, Mar  2 2016, 00:45:44) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocess import Pool
>>> p = Pool(4)
>>> p.map(lambda x: (lambda y:y**2)(x) + x, range(4))
[0, 2, 6, 12]
>>> import multiprocess
>>> multiprocess.__version__
'0.70.5.dev0'
>>> import _multiprocess
```
So I can't tell why it doesn't work for you with the information you have given.  Maybe you had silent build errors?  Are you working in a virtual environment?  Can you give me more info that might help diagnose your issue?

**Comment by evanfoster** [comment]
I'm running into this same issue as well. Happens whether multiprocess is installed globally or in a virtualenv. Installed via pip. Happens whether I use 0.70.4 or 0.70.5.dev0.

OS: Arch Linux

```
$ python --version
Python 3.5.1
```

```
>>> from multiprocess import Pool

>>> p = Pool(4)

>>> p.map(lambda x: (lambda y:y**2)(x) + x, range(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/site-packages/multiprocess/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/site-packages/multiprocess/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/lib/python3.5/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/site-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/site-packages/dill/dill.py", line 793, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python3.5/pickle.py", line 599, in save_reduce
    save(args)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/site-packages/dill/dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
  File "/usr/lib/python3.5/site-packages/multiprocess/pool.py", line 492, in __reduce__
    'pool objects cannot be passed between processes or pickled'
NotImplementedError: pool objects cannot be passed between processes or pickled
pool objects cannot be passed between processes or pickled

>>> import multiprocess

>>> multiprocess.__version__
'0.70.5.dev0'
```

Let me know what other information you need, I'm more than happy to run any commands you'd like.

**Comment by evanfoster** [comment]
Ahh, looks like it might have been the result of using ptpython or bpython instead of the regular python REPL. I saw an error relating to pickling greenlets which tipped me off as none of my code uses greenlets, but bpython does. Might be good to let people know that if they're going to mess with multiprocess in a REPL that they need to do it in the standard python REPL, nothing fancy.

This could also be completely unrelated to the OP's issues.

**Comment by mmckerns** [comment]
@evanfoster: Thanks for the follow-up.  No response from the OP, and I can't reproduce the issue in cpython, so I'm going to close this issue.  I don't test in ptpython or bpython, and I don't know how `dill` performs in those environments.
