### ISSUE TITLE
failures for test_multiprocessing_main_handling

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/multiprocess#28]
all tests in `test_multiprocessing_main_handling` fail for py3.4, py3.5, py3.6, and py3.7.

```
$ python py3.5/tests/test_multiprocessing_main_handling.py 
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
======================================================================
FAIL: test_basic_script (__main__.ForkCmdLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "py3.5/tests/test_multiprocessing_main_handling.py", line 161, in test_basic_script
    self._check_script(script_name)
  File "py3.5/tests/test_multiprocessing_main_handling.py", line 155, in _check_script
    rc, out, err = assert_python_ok(*run_args, __isolated=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/test/support/script_helper.py", line 135, in assert_python_ok
    return _assert_python(True, *args, **env_vars)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/test/support/script_helper.py", line 121, in _assert_python
    err))
AssertionError: Process return code is 1
command line: ['/opt/local/bin/python3.5', '-X', 'faulthandler', '-E', '/private/var/folders/t2/nsd68bs92ys2q1qbjnqf4s6c0000gn/T/tmpbp5kt9jk/script.py', 'fork']

stdout:
---

---

stderr:
---
Traceback (most recent call last):
  File "/private/var/folders/t2/nsd68bs92ys2q1qbjnqf4s6c0000gn/T/tmpbp5kt9jk/script.py", line 10, in <module>
    from multiprocess import Pool, set_start_method
ImportError: No module named 'multiprocess'
---

…
```

**Comment by mmckerns** [comment]
I've not seen this in the wild, except for it being exposed in the tests.
