### ISSUE TITLE
Issue on trying to install

### ISSUE THREAD

**Issue by anistark** [uqfoundation/multiprocess#52]
Ran `pip install multiprocessing`.

Received err:

```
Collecting multiprocessing
  Using cached https://files.pythonhosted.org/packages/b8/8a/38187040f36cec8f98968502992dca9b00cc5e88553e01884ba29cbe6aac/multiprocessing-2.6.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/05/254ppq656dnfc4rl_nfv84sr0000gn/T/pip-install-9dzh3cfr/multiprocessing/setup.py", line 94
        print 'Macros:'
                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int 'Macros:')?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/05/254ppq656dnfc4rl_nfv84sr0000gn/T/pip-install-9dzh3cfr/multiprocessing/
```

**Comment by mmckerns** [comment]
It seems you are trying to install `multiprocessing`, which is a STL python module (i.e. it comes installed with python already).  Did you mean `pip install multiprocess`?

**Comment by mmckerns** [comment]
Please reopen the issue if this is anything other than a typo.
