### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Brave731** [uqfoundation/multiprocess#54]
Hi, 
    I have a question, i use multiprocess==0.70.7, have an error. But running normally on another machine. Have you good iead?
##############
sh-4.2$ python main.py
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    counter = mp.Value('i', 0)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/context.py", line 135, in Value
    ctx=self.get_context())
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/sharedctypes.py", line 73, in Value
    obj = RawValue(typecode_or_type, *args)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/sharedctypes.py", line 48, in RawValue
    obj = _new_value(type_)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/sharedctypes.py", line 40, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/heap.py", line 248, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/heap.py", line 230, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/heap.py", line 128, in _malloc
    arena = Arena(length)
  File "/home/admin/.local/lib/python3.6/site-packages/multiprocess/heap.py", line 81, in __init__
    self.buffer = mmap.mmap(self.fd, self.size)
FileNotFoundError: [Errno 2] No such file or directory
################

**Comment by mmckerns** [comment]
@Brave731: When creating a ticket, please provide a minimal example of the code that generates the error, as well as the traceback.  You've given me the traceback, but not the code, so it's hard to help you.  Looks like you are creating a shared memory `Value`, but beyond that, I can't discern what you are doing because the remaining trace is all relevant to trying to build the `Value`.  The error is finally when trying to build a memory map object (e.g a buffer), and there not being a relevant file descriptor of that name... so it could be that it's expecting to read a file, but one doesn't exist.  That's the best I can do without seeing some minimal example that produces your error.

**Comment by mmckerns** [comment]
Please reopen this issue if it is not resolved.
