### ISSUE TITLE
imap freezes; Ctrl-C raises `IndexError: pop from an empty deque` on L733 of pool.py; (on Ubuntu py3.6.7 and OSX py3.7.3)

### ISSUE THREAD

**Issue by eric-downes** [uqfoundation/multiprocess#57]
Using `mp.Pool().imap` never completes one iteration nor times out on job that takes `mp.Pool().map` less than a few seconds

Example:
(  python 3.7.3 
   installed via brew on OSX 10.13.6, 2017 MacBook Pro, 
   multiprocessing==0.70.7 )

```
$ cat test.py 
import multiprocessing as mp
def fcn(x):
    return x**2
with mp.Pool() as p: 
    y = p.imap(fcn, range(4)) 
for n in y: print(n)   

$ date +%s; python3 test.py; date +%s  
1559342637

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 733, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    for n in y: print(n)   
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 737, in next
    self._cond.wait(timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
1559342674
```

`python -m multiprocess.tests` appears to suffer the same problem, and fail on the same line during keyboard interrupt

However:

```
$ cat test.py; date +%s; python3 test.py; date +%s
import multiprocessing as mp
def fcn(x):
    return x**2
with mp.Pool() as p: 
    y = p.map(fcn, range(4)) 
for n in y: print(n)   
1559510157
0
1
4
9
1559510159
```

Finally, I am experiencing the identical issue on an AWS rd5 running Ubuntu 18.04.2 LTS with python3.6.7 and an unknown version of multiprocessing (doesn't show up in `pip3 freeze`, and module has no `__version__` attribute)

using map works:
```
$ cat test.py; date +%s; python3 test.py; date +%s;
import multiprocessing as mp
def fcn(x):
    return x**2
with mp.Pool() as p: 
    y = p.map(fcn, [0,1,2,3]) 
for n in y: print(n)   
1559511803
0
1
4
9
1559511803
```

yet:
```
$ cat test.py; date +%s; python3 test.py; date +%s; python3 --version
import multiprocessing as mp
def fcn(x):
    return x**2
with mp.Pool() as p: 
    y = p.imap(fcn, [0,1,2,3]) 
for n in y: print(n)   
1559511462
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 746, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    for n in y: print(n)   
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 750, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
1559511740
Python 3.6.7
```

Thanks!

**Comment by eric-downes** [comment]
The problem is that the use of the iterator y needs to be within the context of the `with` resource manager.  DUH.  Otherwise the workers are closed by the time iteration begins.

**Comment by mmckerns** [comment]
Thanks for submitting.  I'm glad you solved it.
