### ISSUE TITLE
fails to lookup references in main with py3.8

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/multiprocess#63]
A lookup of a reference to `__main__` succeeds in 3.7 and earlier...
```
Python 3.7.4 (default, Jul 11 2019, 01:07:12) 
[Clang 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> xrange = range
>>> 
>>> def foo(x):
...   for i in xrange(x):
...     pass
...   return i*i
... 
>>> import multiprocess as mp
>>> import dill
>>> dill.detect.trace(True)
>>> 
>>> mp.Pool(1).map(foo, range(1,2))
F2: <function mapstar at 0x10c7b0830>
# F2
F1: <function foo at 0x10c7b0170>
F2: <function _create_function at 0x10ca4b5f0>
# F2
Co: <code object foo at 0x10c4f2420, file "<stdin>", line 1>
T1: <class 'code'>
F2: <function _load_type at 0x10ca4b4d0>
# F2
# T1
# Co
D1: <dict object at 0x10c520d20>
# D1
D2: <dict object at 0x10cee5820>
# D2
# F1
D2: <dict object at 0x10c5856e0>
# D2
[0]
```
but fails thusly in 3.8 (tested b1 and b2):
```
>>> mp.Pool(1).map(foo, range(1,2))
D2: <dict object at 0x10f201080>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.context.SpawnProcess'>
# T4
D2: <dict object at 0x10f2205c0>
D2: <dict object at 0x10f220480>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
F2: <function worker at 0x10f1f84c0>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
F2: <function rebuild_connection at 0x10f1f81f0>
# F2
T4: <class 'multiprocess.popen_spawn_posix._DupFd'>
# T4
D2: <dict object at 0x10f24ebc0>
# D2
D2: <dict object at 0x10f245e40>
# D2
T4: <class 'multiprocess.synchronize.Lock'>
# T4
D2: <dict object at 0x10f2518c0>
# D2
D2: <dict object at 0x10f251680>
# D2
D2: <dict object at 0x10f220500>
# D2
# D2
F2: <function mapstar at 0x10f0ffd30>
# F2
F1: <function foo at 0x10edb3dc0>
F2: <function _create_function at 0x10f063550>
# F2
Co: <code object foo at 0x10edb1d40, file "<stdin>", line 1>
T1: <class 'code'>
F2: <function _load_type at 0x10f063430>
# F2
# T1
# Co
D1: <dict object at 0x10eb5edc0>
# D1
D2: <dict object at 0x10f256400>
# D2
# F1
D2: <dict object at 0x10f25e400>
# D2
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.8/site-packages/multiprocess-0.70.9.dev0-py3.8-macosx-10.8-x86_64.egg/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mmckerns/lib/python3.8/site-packages/multiprocess-0.70.9.dev0-py3.8-macosx-10.8-x86_64.egg/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "<stdin>", line 2, in foo
NameError: name 'xrange' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.8/site-packages/multiprocess-0.70.9.dev0-py3.8-macosx-10.8-x86_64.egg/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/mmckerns/lib/python3.8/site-packages/multiprocess-0.70.9.dev0-py3.8-macosx-10.8-x86_64.egg/multiprocess/pool.py", line 768, in get
    raise self._value
NameError: name 'xrange' is not defined
>>> 
```

**Comment by mmckerns** [comment]
It also appears that there are leaked semaphores in 3.8 -- I believe this was also seen in `multiprocessing` under testing, but I should check.

**Comment by mmckerns** [comment]
Interestingly, replacing `xrange` with `range` (so function will pickle without dangling references) shows the function is prefaced with a number of serialized items:
```
>>> def bar(x):
...   for i in range(x):
...     pass
...   return i*i
... 
>>> mp.Pool(1).map(bar, [1])
D2: <dict object at 0x10a0ea3c0>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
T4: <class 'multiprocess.context.SpawnProcess'>
# T4
D2: <dict object at 0x10a0e0f00>
D2: <dict object at 0x10a0ea2c0>
T4: <class 'multiprocess.process.AuthenticationString'>
# T4
# D2
F2: <function worker at 0x10a0834c0>
# F2
T4: <class 'multiprocess.queues.SimpleQueue'>
# T4
F2: <function rebuild_connection at 0x10a0831f0>
# F2
T4: <class 'multiprocess.popen_spawn_posix._DupFd'>
# T4
D2: <dict object at 0x10a0ea640>
# D2
D2: <dict object at 0x10a0ea580>
# D2
T4: <class 'multiprocess.synchronize.Lock'>
# T4
D2: <dict object at 0x10a0ea7c0>
# D2
D2: <dict object at 0x10a0ea8c0>
# D2
D2: <dict object at 0x10a0ea300>
# D2
# D2
F2: <function mapstar at 0x109f88d30>
# F2
F1: <function bar at 0x10a0e7040>
F2: <function _create_function at 0x109ecc310>
# F2
Co: <code object bar at 0x10a0cdb30, file "<stdin>", line 1>
T1: <class 'code'>
F2: <function _load_type at 0x109ecc1f0>
# F2
# T1
# Co
D1: <dict object at 0x1099e3dc0>
# D1
D2: <dict object at 0x10a0ef380>
# D2
# F1
D2: <dict object at 0x10a0e0240>
# D2
[0]
>>> 
```
