### ISSUE TITLE
OSX Queue limited to 32768

### ISSUE THREAD

**Issue by cbitterfield** [uqfoundation/multiprocess#66]
This issue seems to be a carry through from the Multiprocessing library. It does not exist in the queue.Queue library. It does not exist in Linux. 

I am trying to determine if this is a library limitation, OSX limitation, or a OSX configurable parameter.

```
Python 3.7.5 (default, Oct 19 2019, 01:20:12)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import queue
>>> import multiprocessing
>>>
>>>
>>> mQ = multiprocessing.Queue(32767)
>>> mQ2 = multiprocessing.Queue(32768)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 48, in __init__
    self._sem = ctx.BoundedSemaphore(maxsize)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 87, in BoundedSemaphore
    return BoundedSemaphore(value, ctx=self.get_context())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 145, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value, ctx=ctx)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 22] Invalid argument
>>> QQ=queue.Queue(32767)
>>> QQ2=queue.Queue(32768)
>>> QQ2=queue.Queue(65535)```


OSX Configuration Parameters for Semaphores: (sysctl)

```
bash-3.2# sysctl -a | grep sysv
kern.sysv.shmmax: 524288000
kern.sysv.shmmin: 1
kern.sysv.shmmni: 64
kern.sysv.shmseg: 32
kern.sysv.shmall: 131072000
kern.sysv.semmni: 87381
kern.sysv.semmns: 130
kern.sysv.semmnu: 87381
kern.sysv.semmsl: 87381
kern.sysv.semume: 10
security.mac.sysvmsg_enforce: 1
security.mac.sysvsem_enforce: 1
security.mac.sysvshm_enforce: 1
```

IPC Information
```
IPC status from <running system> as of Tue Nov  5 09:20:27 PST 2019
seminfo:
	semmap:     30	(# of entries in semaphore map)
	semmni:     24	(# of semaphore identifiers)
	semmns:     64	(# of semaphores in system)
	semmnu:     32	(# of undo structures in system)
	semmsl:  87381	(max # of semaphores per id)
	semopm:      5	(max # of operations per semop call)
	semume:     10	(max # of undo entries per process)
	semusz:     32	(size in bytes of undo structure)
	semvmx:  32767	(semaphore maximum value)
	semaem:  16384	(adjust on exit max value)
```

**Comment by mmckerns** [comment]
It's not a library limitation, it's OSX.  I'm closing this. Please reopen if there's more to add.
