### ISSUE TITLE
pypy3 testing hangs on travis

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/multiprocess#88]
`pypy3` on travis is currently `pypy3.6-7.3.1`, and it hangs on testing.
Tried `pypy3.6-7.3.3` and `pypy3.6-7.1.1` and see the same behavior.
Was unable to test against `pypy3.7`.

**Comment by mmckerns** [comment]
It's either for forkserver or spawn... so those could be skipped.  It passes the default environment.

**Comment by mmckerns** [comment]
```
multiprocess/tests/test_multiprocessing_fork.py
.........s......s................s..ss......s...................s.s....s.....ss.....s.....s.........s...s......s..........ss......................................ss.........ss..s...........................s...s......s...ssss...........................s....ss..ss..ss..sss.....s....s.
----------------------------------------------------------------------
Ran 283 tests in 49.843s
```

```
multiprocess/tests/test_multiprocessing_forkserver.py
.........s....Traceback (most recent call last):
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/semaphore_tracker.py", line 132, in main
    cache.remove(name)
KeyError: b'/mp-53h5l_0r'
Traceback (most recent call last):
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/semaphore_tracker.py", line 132, in main
    cache.remove(name)
KeyError: b'/mp-b9wcjo7x'
Traceback (most recent call last):
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/semaphore_tracker.py", line 132, in main
    cache.remove(name)
KeyError: b'/mp-ta5v3n0g'
Traceback (most recent call last):
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/semaphore_tracker.py", line 132, in main
    cache.remove(name)
KeyError: b'/mp-6_nh31rb'
...................s..ss......s...................s.s....s.....ss.....s.....s.........s...s......s..........ss...............Traceback (most recent call last):
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/forkserver.py", line 196, in main
    _serve_one(s, listener, alive_r, old_handlers)
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/forkserver.py", line 231, in _serve_one
    code = spawn._main(child_r)
  File "/home/travis/build/uqfoundation/multiprocess/pypy3.6/multiprocess/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/travis/virtualenv/pypy3.6-7.3.1/site-packages/dill-0.3.4-py3.6.egg/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/travis/virtualenv/pypy3.6-7.3.1/site-packages/dill-0.3.4-py3.6.egg/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "/opt/python/pypy3.6-7.3.1/lib-python/3/pickle.py", line 1070, in load
    dispatch[key[0]](self)
  File "/opt/python/pypy3.6-7.3.1/lib-python/3/pickle.py", line 1418, in load_reduce
    stack[-1] = func(*args)
TypeError: unhashable type: 'UserDict'
```
